version: '3'
services:
  frontend:
    image: "frontend:latest"
    ports:
    - "8000:8000"
  backend:
    image: "backend:latest"
    ports:
    - "5000:5000"
  proxy:
    image: "proxy:latest"
    ports:
    - "80:80"
